### ISSUE TITLE
Opposite plugin

### ISSUE THREAD

**Issue by SetiZ** [ember-cli/babel-plugin-filter-imports#254]
Hello,
This plugin really works well, but I have a question about it: Is there a plugin who instead of removing, adds imports to the build.
In my project I need to add some polyfills automatically and I wanted to do it directly from Babel.
I am sorry if this is not the right way to ask it ^^

**Comment by layershifter** [comment]
Actually, the polyfill case it should be done by `preset-env`: https://babeljs.io/docs/en/babel-preset-env#usebuiltins

I don't know about plugins that can solve mentioned case 🤔 May be it will be better to try ask about it on StackOverflow...
